/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LoginHandler;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 * 로그인하는 화면을 보여주는 Boundary 클래스.
 *
 * @author Sungrae
 */
public class LoginView extends javax.swing.JFrame {

    ProfessorView professor;
    CourseView course;
    StudentView student;
    LoginHandler lHandler;

    String id;
    String pwd;
    String name;

    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();

        setTitle("대학 정보 시스템");
        setVisible(true);
        setResizable(false); //프레임 크기 조정 x
        setLocationRelativeTo(null); //프레임을 중앙으로 배치.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLoginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        u_id = new javax.swing.JTextField();
        u_pwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLoginBtn.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLoginBtn.setText("확인");
        jLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("굴림", 0, 48)); // NOI18N
        jLabel1.setText("대학 정보 시스템");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(u_id)
                            .addComponent(u_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLoginBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(u_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(u_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginBtnActionPerformed
        id = u_id.getText().trim();
        pwd = u_pwd.getText().trim();
        try {
            // TODO add your handling code here:
            switch (u_id.getText(0, 1)) {
                case "S":
                    lHandler = new LoginHandler();
                    if (lHandler.setStuInfo(id, pwd) == true) {
                        name = lHandler.getName();
                        JOptionPane.showMessageDialog(null, name + " 학생님 환영합니다.", "알림", JOptionPane.PLAIN_MESSAGE);
                        student = new StudentView(id);
                        id = null;
                        pwd = null;
                        u_id.setText("");
                        u_pwd.setText("");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null,
                                "아이디,비밀번호가 틀렸습니다.\n   값을 올바르게 입력하세요.", "경고",
                                JOptionPane.WARNING_MESSAGE);
                        break;
                    }
                case "P":
                    lHandler = new LoginHandler();
                    if (lHandler.setProfInfo(id, pwd) == true) {
                        name = lHandler.getName();
                        JOptionPane.showMessageDialog(null, name + " 교수님 환영합니다.", "알림", JOptionPane.PLAIN_MESSAGE);
                        professor = new ProfessorView(id);
                        id = null;
                        pwd = null;
                        u_id.setText("");
                        u_pwd.setText("");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null,
                                "아이디,비밀번호가 틀렸습니다.\n   값을 올바르게 입력하세요.", "경고",
                                JOptionPane.WARNING_MESSAGE);
                        break;
                    }
                case "H":
                    lHandler = new LoginHandler();
                    if (lHandler.setHakInfo(id, pwd) == true) {
                        name = lHandler.getName();
                        JOptionPane.showMessageDialog(null, name + " 학사 담당자님 환영합니다.", "알림", JOptionPane.PLAIN_MESSAGE);
                        HaksaView hv = new HaksaView(id);
                        id = null;
                        pwd = null;
                        u_id.setText("");
                        u_pwd.setText("");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null,
                                "아이디,비밀번호가 틀렸습니다.\n   값을 올바르게 입력하세요.", "경고",
                                JOptionPane.WARNING_MESSAGE);
                        break;
                    }
                case "G":
                    lHandler = new LoginHandler();
                    if (lHandler.setSubInfo(id, pwd) == true) {
                        name = lHandler.getName();
                        JOptionPane.showMessageDialog(null, name + " 수업 담당자님 환영합니다.", "알림", JOptionPane.PLAIN_MESSAGE);
                        course = new CourseView(id);
                        id = null;
                        pwd = null;
                        u_id.setText("");
                        u_pwd.setText("");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null,
                                "아이디,비밀번호가 틀렸습니다.\n   값을 올바르게 입력하세요.", "경고",
                                JOptionPane.WARNING_MESSAGE);
                        break;
                    }
                default:
                    JOptionPane.showMessageDialog(null,
                            "아이디,비밀번호가 틀렸습니다.\n   값을 올바르게 입력하세요.", "경고",
                            JOptionPane.WARNING_MESSAGE);
                    break;
            }
        } catch (BadLocationException ex) {
            JOptionPane.showMessageDialog(null,
                    "페이지 호출에 실패하였습니다.", "경고",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jLoginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLoginBtn;
    private javax.swing.JTextField u_id;
    private javax.swing.JPasswordField u_pwd;
    // End of variables declaration//GEN-END:variables
}
