/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ModifyInfoHandler;
import javax.swing.JOptionPane;

/**
 * 비밀번호 수정하는 화면을 보여주는 Boundary 클래스.
 *
 * @author Sungrae
 */
public class ModifyInfoView extends javax.swing.JFrame {

    ModifyInfoHandler mHandler;
    String id;
    String curPwd;
    String newPwd;
    String newPwd1;

    /**
     * Creates new form modifyInfoView
     */
    public ModifyInfoView() {
    }

    public ModifyInfoView(String id) {
        this.id = id;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("비밀번호 변경");
        setVisible(true);
        setResizable(false); //프레임 크기 조정 x
        setLocationRelativeTo(null); //프레임을 중앙으로 배치.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCurPasswordField = new javax.swing.JPasswordField();
        jNewPasswordField = new javax.swing.JPasswordField();
        jNewPasswordField1 = new javax.swing.JPasswordField();
        jChangeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCancelBtn.setText("취소");
        jCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel1.setText("비밀번호 변경");

        jLabel2.setText("현재 비밀번호 : ");

        jLabel3.setText("새 비밀번호 : ");

        jLabel4.setText("새 비밀번호 확인 : ");

        jChangeBtn.setText("변경");
        jChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jChangeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCancelBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCurPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jNewPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCurPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jNewPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChangeBtn)
                    .addComponent(jCancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jCancelBtnActionPerformed

    private void jChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeBtnActionPerformed
        curPwd = jCurPasswordField.getText().trim();
        System.out.println(curPwd);
        newPwd = jNewPasswordField.getText().trim();
        System.out.println(newPwd);
        newPwd1 = jNewPasswordField1.getText().trim();
        System.out.println(newPwd1);
        mHandler = new ModifyInfoHandler();

        switch (id.substring(0, 1)) {
            case "S":
                if (mHandler.setStuModifyInfoHandler(id, curPwd, newPwd, newPwd1) == true) {
                    JOptionPane.showMessageDialog(null, "비밀번호를 변경하셨습니다.", "알림", JOptionPane.PLAIN_MESSAGE);
                    this.dispose();
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "비밀번호를 잘못 입력하셨습니다.", "경고", JOptionPane.WARNING_MESSAGE);
                    break;
                }
            case "P":
                if (mHandler.setProfModifyInfoHandler(id, curPwd, newPwd, newPwd1) == true) {
                    JOptionPane.showMessageDialog(null, "비밀번호를 변경하셨습니다.", "알림", JOptionPane.PLAIN_MESSAGE);
                    this.dispose();
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "비밀번호를 잘못 입력하셨습니다.", "경고", JOptionPane.WARNING_MESSAGE);
                    break;
                }
            case "H":
                if (mHandler.setHakModifyInfoHandler(id, curPwd, newPwd, newPwd1) == true) {
                    JOptionPane.showMessageDialog(null, "비밀번호를 변경하셨습니다.", "알림", JOptionPane.PLAIN_MESSAGE);
                    this.dispose();
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "비밀번호를 잘못 입력하셨습니다.", "경고", JOptionPane.WARNING_MESSAGE);
                    break;
                }
            case "G":
                if (mHandler.setSubModifyInfoHandler(id, curPwd, newPwd, newPwd1) == true) {
                    JOptionPane.showMessageDialog(null, "비밀번호를 변경하셨습니다.", "알림", JOptionPane.PLAIN_MESSAGE);
                    this.dispose();
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "비밀번호를 잘못 입력하셨습니다.", "경고", JOptionPane.WARNING_MESSAGE);
                    break;
                }
            default:
                JOptionPane.showMessageDialog(null, "비밀번호를 잘못 입력하셨습니다.", "경고", JOptionPane.WARNING_MESSAGE);
                break;
        }
    }//GEN-LAST:event_jChangeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JButton jChangeBtn;
    private javax.swing.JPasswordField jCurPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jNewPasswordField;
    private javax.swing.JPasswordField jNewPasswordField1;
    // End of variables declaration//GEN-END:variables
}
