package view;

import controller.ProfInfoHandler;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 교수가 자신이 강의하는 강좌들을 볼 수 있는 Boundary Class.
 *
 * @author 박지동
 */
public class ProfessorView extends javax.swing.JFrame {

    /**
     * Creates new form Professor
     */
    DefaultTableModel model; //테이블을 만든다
    ModifyInfoView modifyInfo;
    ProfInfoHandler pHandler = new ProfInfoHandler();
    AttendListView attendListView;
    StuListView stuListview;

    String p_id;
    String c_id;
    String title;

    public ProfessorView() {
    }

    public ProfessorView(String id) {
        this.p_id = id;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        setTitle("성적 관리");
        setVisible(true);
        setResizable(false); //프레임 크기 조정 x
        setLocationRelativeTo(null); //프레임을 중앙으로 배치.
        model = (DefaultTableModel) this.infoTable.getModel();

        model.setNumRows(0); //테이블에 정보가 중복해서 저장되지 않도록 테이블 초기화
        if (pHandler.showCourseState(p_id) == true) {
            for (int i = 0; i < pHandler.getCourseInfoData().size(); i = i + 5) {
                model.addRow(new Object[]{
                    pHandler.getCourseInfoData().get(i),
                    pHandler.getCourseInfoData().get(i + 1),
                    pHandler.getCourseInfoData().get(i + 2),
                    pHandler.getCourseInfoData().get(i + 3),
                    pHandler.getCourseInfoData().get(i + 4)
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "테이블 조회에 실패하였습니다.", "테이블 조회 실패", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructP1or to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jChangePassword = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();
        jStuListBtn = new javax.swing.JButton();
        jAttendListBtn = new javax.swing.JButton();
        jCancelBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jChangePassword.setText("비밀번호 변경");
        jChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangePasswordActionPerformed(evt);
            }
        });

        infoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "강좌번호", "강좌이름", "학점 수", "최소 학생 수", "최대 학생 수"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        infoTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(infoTable);
        if (infoTable.getColumnModel().getColumnCount() > 0) {
            infoTable.getColumnModel().getColumn(0).setResizable(false);
            infoTable.getColumnModel().getColumn(1).setResizable(false);
            infoTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            infoTable.getColumnModel().getColumn(2).setResizable(false);
            infoTable.getColumnModel().getColumn(3).setResizable(false);
            infoTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jStuListBtn.setText("학생 명단 조회");
        jStuListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStuListBtnActionPerformed(evt);
            }
        });

        jAttendListBtn.setText("출석부 조회");
        jAttendListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAttendListBtnActionPerformed(evt);
            }
        });

        jCancelBtn.setText("닫기");
        jCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        jLabel2.setText("성적 관리");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jChangePassword))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAttendListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jStuListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChangePassword)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jStuListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAttendListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangePasswordActionPerformed
        // TODO add your handling code here:
        modifyInfo = new ModifyInfoView(p_id);
    }//GEN-LAST:event_jChangePasswordActionPerformed

    private void jStuListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStuListBtnActionPerformed
        // TODO add your handling code here:
        if (infoTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "강좌를 선택해주세요.", "강좌 선택 실패", JOptionPane.WARNING_MESSAGE);
        } else {
            int row = infoTable.getSelectedRow();
            c_id = (String) infoTable.getValueAt(row, 0);

            stuListview = new StuListView(c_id);
        }
    }//GEN-LAST:event_jStuListBtnActionPerformed

    private void jAttendListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAttendListBtnActionPerformed
        // TODO add your handling code here:
        if (infoTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "강좌를 선택해주세요.", "강좌 선택 실패", JOptionPane.WARNING_MESSAGE);
        } else {
            int row = infoTable.getSelectedRow();
            c_id = (String) infoTable.getValueAt(row, 0);
            title = (String) infoTable.getValueAt(row, 1);

            attendListView = new AttendListView(c_id, title);
        }
    }//GEN-LAST:event_jAttendListBtnActionPerformed

    private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jCancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable infoTable;
    private javax.swing.JButton jAttendListBtn;
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JButton jChangePassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jStuListBtn;
    // End of variables declaration//GEN-END:variables
}
