package view;

import controller.StudentInfoHandler;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 성적표를 확인하는 Boundary Class.
 *
 * @author user
 */
public class ScoreCheckView extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    DefaultTableModel model;
    StudentInfoHandler sHandler = new StudentInfoHandler();

    String s_id;

    public ScoreCheckView() {

    }

    public ScoreCheckView(String s_id) {
        this.s_id = s_id;
        System.out.println(s_id);
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        setTitle("성적 확인");
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        model = (DefaultTableModel) this.jScoreTable.getModel();

        model.setNumRows(0); //테이블에 정보가 중복해서 저장되지 않도록 테이블 초기화
        if (sHandler.getScoreInfo(s_id) == true) {
            for (int i = 0; i < sHandler.getScoreInfoData().size(); i = i + 7) {
                model.addRow(new Object[]{
                    sHandler.getScoreInfoData().get(i),
                    sHandler.getScoreInfoData().get(i + 1),
                    sHandler.getScoreInfoData().get(i + 2),
                    sHandler.getScoreInfoData().get(i + 3),
                    sHandler.getScoreInfoData().get(i + 4),
                    sHandler.getScoreInfoData().get(i + 5),
                    sHandler.getScoreInfoData().get(i + 6),
                    Boolean.FALSE
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "테이블 조회에 실패하였습니다.", "테이블 조회 실패", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScoreTable = new javax.swing.JTable();
        jCloseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        jLabel1.setText("성적확인");

        jScoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "강좌번호", "강좌이름", "담당학과", "학점 수", "담당교수", "학점", "학점 값"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScoreTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jScoreTable);
        if (jScoreTable.getColumnModel().getColumnCount() > 0) {
            jScoreTable.getColumnModel().getColumn(0).setResizable(false);
            jScoreTable.getColumnModel().getColumn(1).setResizable(false);
            jScoreTable.getColumnModel().getColumn(2).setResizable(false);
            jScoreTable.getColumnModel().getColumn(3).setResizable(false);
            jScoreTable.getColumnModel().getColumn(4).setResizable(false);
            jScoreTable.getColumnModel().getColumn(5).setResizable(false);
            jScoreTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jCloseBtn.setText("닫기");
        jCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCloseBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseBtnActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jCloseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCloseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jScoreTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
